### ISSUE TITLE
Quick update on optimization + pipeline functions/testing

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/wine-origin-prediction#18]
Hi team!

Quick update - currently working on the assigned optimization modularization and testing in branch `function_optimization`. Decided to prioritize making the optimization component thorough, and then repeating for pipeline modularization and testing if time allows tomorrow afternoon. Hoping to make my PR for optimization tomorrow morning!

**Comment by hbandukw** [comment]
Sounds good @juliaeveritt 🥇

**Comment by hbandukw** [comment]
@juliaeveritt - let me know how you are returning the cv scores so I can modify my accuracy curve function accordingly :)

**Comment by juliaeveritt** [comment]
@hbandukw just pushed completed draft to `function_optimization` ! Tried to follow same format as report returning the gridsearchcv object with .cv_results_ method to get the scores
