### ISSUE TITLE
Nov 18 update

### ISSUE THREAD

**Issue by hbandukw** [UBC-MDS/wine-origin-prediction#7]
Hi everyone- I have done the following:
1- added the "Analysis" section to the google doc - https://docs.google.com/document/d/1vY8POcTi43uW1HfF5aQ3oGD1Mel6lKHL51PPF1fCDRI/edit.
2- I have added both in-text citations for "Analysis", "Introduction" and "Data" plus the full APA-style citations under "References" in the google doc.
(This includes the few papers I had linked directly in our report notebook)
3- Clarification needed: Originally the google doc did not say "done" under "introduction" even though it is completed. I just want to double check if anything else other than what I have included in the report notebook needs to be added?
anyway, let me know if there was anything else you all discussed that I may have missed :smiley:

**Comment by juliaeveritt** [comment]
Thanks Hina! I've moved everything into src/report.ipynb and done some formatting in the new 'consolidation branch' - made a PR whenever somebody has a chance to review it!
