### ISSUE TITLE
Milestone 2 Planning

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/wine-origin-prediction#9]
Components (taken from [here](https://pages.github.ubc.ca/MDS-2023-24/DSCI_522_dsci-workflows_students/release/milestone2/milestone2.html))

1. Upgrade your project’s computational environment to a container.

2. Abstract some code from your literate code document (*.Rmd, *.qmd, *.ipynb, etc) to functions a modular file (e.g., .R or .py) and write tests to make sure they are robust!

3. Render your report to a PDF or HTML document and link to it from your README.

**Comment by juliaeveritt** [comment]
Part 1:
- to do this, we can use the Dockerfile COPY command
- @sean-m-mckay will take this on

**Comment by juliaeveritt** [comment]
Part 2: 
- each team member will chose one element of the analysis to put into a function and test
- preprocessing - @YimengXia 
- EDA - distribution plots @sean-m-mckay 
- making the pipeline - @juliaeveritt 
- model optimization - @juliaeveritt 
- plotting the accuracy curve - @hbandukw

**Comment by juliaeveritt** [comment]
Part 3:
- render report to html (use Git Pages) and link to it in the README at end @hbandukw 

Other:
- add credit to environment.yml @sean-m-mckay
- update README with instructions on how to use our container image @YimengXia

**Comment by hbandukw** [comment]
@sean-m-mckay - can we do the docker image together?

**Comment by sean-m-mckay** [comment]
> @sean-m-mckay - can we do the docker image together?

Sure! let's work on it tomorrow at lunch?
